In [2]:
import numpy as np

In [5]:
lst=[1,2,3,4]
arr=np.array(lst)

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [11]:
lst1=[1,2,3,4,5]
lst2=[6,2,3,4,5]
lst3=[6,7,3,4,5]

arr1=np.array([lst1,lst2,lst3])

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 2, 3, 4, 5],
       [6, 7, 3, 4, 5]])

In [13]:
arr1.shape

(3, 5)

In [14]:
#indexing
arr[3]

4

In [15]:
arr[3]=5

In [16]:
arr

array([1, 2, 3, 5])

In [17]:
arr[1:3]

array([2, 3])

In [18]:
arr[-1]

5

In [19]:
arr[:-1]

array([1, 2, 3])

In [20]:
arr[::-1]

array([5, 3, 2, 1])

In [21]:
arr[::-2]

array([5, 2])

In [22]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 2, 3, 4, 5],
       [6, 7, 3, 4, 5]])

In [24]:
arr1[:,1]

array([2, 2, 7])

In [26]:
arr1[1:,1:3]

array([[2, 3],
       [7, 3]])

In [34]:
arr1[1:,]

array([[6, 2, 3, 4, 5],
       [6, 7, 3, 4, 5]])

In [36]:
arr1[:,3:]

array([[4, 5],
       [4, 5],
       [4, 5]])

In [37]:
#EDA
arr

array([1, 2, 3, 5])

In [38]:
arr<2

array([ True, False, False, False])

In [39]:
arr[arr<2]

array([1])

In [40]:
arr1.shape

(3, 5)

In [41]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7],
       [3, 4, 5]])

In [49]:
#Mechanism to create an array
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [51]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [52]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [55]:
arr

array([1, 2, 3, 5])

In [54]:
arr *arr

array([ 1,  4,  9, 25])

In [56]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 2, 3, 4, 5],
       [6, 7, 3, 4, 5]])

In [57]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [12,  4,  6,  8, 10],
       [12, 14,  6,  8, 10]])

In [60]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
#Always a random number
np.random.randint(10,50)

49

In [77]:
np.random.randint(10,50,4)

array([15, 33, 41, 13])

In [79]:
np.random.randint(10,50,4).reshape(2,2)

array([[15, 41],
       [31, 18]])

In [81]:
np.random.rand(5,6)

array([[2.43324544e-01, 3.97675042e-02, 6.16375230e-01, 1.88090895e-02,
        3.25640073e-01, 1.69628398e-01],
       [7.91382737e-01, 5.83850361e-01, 3.34285336e-01, 8.32635871e-01,
        2.10731145e-03, 4.07642071e-01],
       [3.49278447e-02, 2.64309124e-01, 1.57728532e-01, 9.44779755e-01,
        5.37934809e-01, 7.60623979e-01],
       [9.12782317e-01, 3.62870977e-01, 7.33058419e-01, 5.64107874e-01,
        6.16309557e-01, 8.69436620e-01],
       [5.30043389e-01, 2.94900120e-01, 8.78867441e-01, 5.25483523e-06,
        2.20493539e-01, 4.34495510e-01]])

In [82]:
np.random.random_sample((4,7))

array([[8.87822209e-01, 8.84756482e-01, 5.28379921e-02, 2.91816731e-01,
        5.62844219e-01, 7.66620033e-02, 2.36306940e-01],
       [7.00022796e-01, 7.46026499e-01, 7.09738638e-01, 1.43105908e-01,
        7.38577754e-01, 2.73303463e-01, 6.32422298e-01],
       [6.22189282e-01, 8.51616085e-01, 1.58426975e-01, 5.17837516e-02,
        6.25767399e-01, 5.98056069e-01, 3.23828399e-01],
       [7.26291070e-01, 5.53790093e-01, 3.63604048e-01, 2.29188710e-01,
        2.37608144e-04, 3.25755884e-01, 5.46494752e-01]])